name: masihokeh
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^1.1.0
  liquid_pull_to_refresh: ^1.1.1
  fancy_bottom_navigation: ^0.3.2
  fluro: ^1.4.0
  carousel_pro: ^0.0.13
  font_awesome_flutter: ^8.2.0
  flutter_swiper: ^1.1.4
  polygon_clipper: ^1.0.1
  flutter_range_slider: "^1.1.0"
  clippy_flutter: ^1.0.0    
  qr_flutter: ^2.0.0
  datetime_picker_formfield: ^0.1.8
  google_sign_in: ^4.0.1+3
  shared_preferences: ^0.5.1+2
  intro_views_flutter: ^2.6.0
  splashscreen: ^1.2.0
  image_picker: ^0.6.0+1
  dropdownfield: 0.0.2
  uuid: 2.0.0
  flutter_signin_button: ^0.2.8
  firebase_storage: ^3.0.6
  firebase_auth: ^0.14.0+4
  fluttertoast: ^3.1.0
  cloud_firestore: ^0.12.9+1
  async_loader: ^0.1.2

  


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/t-shirt-model.png
    - assets/1.jpg
    - assets/2.jpg
    - assets/3.jpg
    - assets/4.jpg
    - assets/5.jpg
    - assets/6.jpg
    - assets/7.jpg
    - assets/indomaret.jpg
    - assets/susu.jpg
    - assets/mie.jpg
    - assets/susu.png
    - assets/sosis1.jpg
    - assets/sosis2.jpg
    - assets/warteg.jpg
    - assets/warteg2.jpg
    - assets/warteg3.jpg
    - assets/warteg4.png
    - assets/warungpintar.png
    - assets/ibis.png
    - assets/logo masihok.png
    - assets/wartegbukan.jpg
    - assets/wartegbukan2.jpg
    - assets/wartegbukan3.jpg
    - assets/wartegbukan4.jpg
    - assets/hotel1.jpg
    - assets/hotel2.jpg
    - assets/sarirotikeju.jpg
    - assets/snacks.jpg
    - assets/tango.jpg
    - assets/fruitdkk.jpg
    - assets/food.jpg
    - assets/drink.jpg
    - assets/76.png
    - assets/pisang.jpg
    - assets/pir.png
    - assets/salak.jpg
    - assets/roti.jpg
    - assets/jambu.jpg
    - assets/apel.jpg
    - assets/logobuah.jpg
  fonts:
    - family: futuras
      fonts:
        - asset: assets/fonts/futura/futura.ttf
    - family: rock
      fonts:
      - asset: assets/fonts/ROCK.ttf
    - family: pacifico
      fonts:
      - asset: assets/fonts/Pacifico.ttf
    - family: roboto
      fonts:
      - asset: assets/fonts/Roboto-Regular.ttf
    - family: opensans
      fonts:
      - asset: assets/fonts/OpenSans-Regular.ttf
    - family: openbold
      fonts:
      - asset: assets/fonts/OpenSans-Bold.ttf
    - family: openlight
      fonts:
      - asset: assets/fonts/OpenSans-Light.ttf
    - family: alegreyaR
      fonts:
      - asset: assets/alegreya-sans/AlegreyaSans-Regular.ttf
    - family: alegreyaB
      fonts:
        - asset: assets/alegreya-sans/AlegreyaSans-Black.ttf
    - family: alegreyaT
      fonts:
        - asset: assets/alegreya-sans/AlegreyaSans-Thin.ttf
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
